/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MantenimientoRouteImport } from './routes/mantenimiento'
import { Route as HistorialRouteImport } from './routes/historial'
import { Route as EquiposRouteImport } from './routes/equipos'
import { Route as CambiarPasswordRouteImport } from './routes/cambiar-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MantenimientoIndexRouteImport } from './routes/mantenimiento.index'
import { Route as MantenimientoParametrosRouteImport } from './routes/mantenimiento.parametros'
import { Route as MantenimientoEquiposExternosRouteImport } from './routes/mantenimiento.equipos-externos'
import { Route as MantenimientoIdRouteImport } from './routes/mantenimiento.$id'
import { Route as InspeccionIdRouteImport } from './routes/inspeccion.$id'
import { Route as MantenimientoNuevoTipoRouteImport } from './routes/mantenimiento.nuevo.$tipo'

const MantenimientoRoute = MantenimientoRouteImport.update({
  id: '/mantenimiento',
  path: '/mantenimiento',
  getParentRoute: () => rootRouteImport,
} as any)
const HistorialRoute = HistorialRouteImport.update({
  id: '/historial',
  path: '/historial',
  getParentRoute: () => rootRouteImport,
} as any)
const EquiposRoute = EquiposRouteImport.update({
  id: '/equipos',
  path: '/equipos',
  getParentRoute: () => rootRouteImport,
} as any)
const CambiarPasswordRoute = CambiarPasswordRouteImport.update({
  id: '/cambiar-password',
  path: '/cambiar-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MantenimientoIndexRoute = MantenimientoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MantenimientoRoute,
} as any)
const MantenimientoParametrosRoute = MantenimientoParametrosRouteImport.update({
  id: '/parametros',
  path: '/parametros',
  getParentRoute: () => MantenimientoRoute,
} as any)
const MantenimientoEquiposExternosRoute =
  MantenimientoEquiposExternosRouteImport.update({
    id: '/equipos-externos',
    path: '/equipos-externos',
    getParentRoute: () => MantenimientoRoute,
  } as any)
const MantenimientoIdRoute = MantenimientoIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => MantenimientoRoute,
} as any)
const InspeccionIdRoute = InspeccionIdRouteImport.update({
  id: '/inspeccion/$id',
  path: '/inspeccion/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MantenimientoNuevoTipoRoute = MantenimientoNuevoTipoRouteImport.update({
  id: '/nuevo/$tipo',
  path: '/nuevo/$tipo',
  getParentRoute: () => MantenimientoRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/cambiar-password': typeof CambiarPasswordRoute
  '/equipos': typeof EquiposRoute
  '/historial': typeof HistorialRoute
  '/mantenimiento': typeof MantenimientoRouteWithChildren
  '/inspeccion/$id': typeof InspeccionIdRoute
  '/mantenimiento/$id': typeof MantenimientoIdRoute
  '/mantenimiento/equipos-externos': typeof MantenimientoEquiposExternosRoute
  '/mantenimiento/parametros': typeof MantenimientoParametrosRoute
  '/mantenimiento/': typeof MantenimientoIndexRoute
  '/mantenimiento/nuevo/$tipo': typeof MantenimientoNuevoTipoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/cambiar-password': typeof CambiarPasswordRoute
  '/equipos': typeof EquiposRoute
  '/historial': typeof HistorialRoute
  '/inspeccion/$id': typeof InspeccionIdRoute
  '/mantenimiento/$id': typeof MantenimientoIdRoute
  '/mantenimiento/equipos-externos': typeof MantenimientoEquiposExternosRoute
  '/mantenimiento/parametros': typeof MantenimientoParametrosRoute
  '/mantenimiento': typeof MantenimientoIndexRoute
  '/mantenimiento/nuevo/$tipo': typeof MantenimientoNuevoTipoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/cambiar-password': typeof CambiarPasswordRoute
  '/equipos': typeof EquiposRoute
  '/historial': typeof HistorialRoute
  '/mantenimiento': typeof MantenimientoRouteWithChildren
  '/inspeccion/$id': typeof InspeccionIdRoute
  '/mantenimiento/$id': typeof MantenimientoIdRoute
  '/mantenimiento/equipos-externos': typeof MantenimientoEquiposExternosRoute
  '/mantenimiento/parametros': typeof MantenimientoParametrosRoute
  '/mantenimiento/': typeof MantenimientoIndexRoute
  '/mantenimiento/nuevo/$tipo': typeof MantenimientoNuevoTipoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/cambiar-password'
    | '/equipos'
    | '/historial'
    | '/mantenimiento'
    | '/inspeccion/$id'
    | '/mantenimiento/$id'
    | '/mantenimiento/equipos-externos'
    | '/mantenimiento/parametros'
    | '/mantenimiento/'
    | '/mantenimiento/nuevo/$tipo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/cambiar-password'
    | '/equipos'
    | '/historial'
    | '/inspeccion/$id'
    | '/mantenimiento/$id'
    | '/mantenimiento/equipos-externos'
    | '/mantenimiento/parametros'
    | '/mantenimiento'
    | '/mantenimiento/nuevo/$tipo'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/cambiar-password'
    | '/equipos'
    | '/historial'
    | '/mantenimiento'
    | '/inspeccion/$id'
    | '/mantenimiento/$id'
    | '/mantenimiento/equipos-externos'
    | '/mantenimiento/parametros'
    | '/mantenimiento/'
    | '/mantenimiento/nuevo/$tipo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  CambiarPasswordRoute: typeof CambiarPasswordRoute
  EquiposRoute: typeof EquiposRoute
  HistorialRoute: typeof HistorialRoute
  MantenimientoRoute: typeof MantenimientoRouteWithChildren
  InspeccionIdRoute: typeof InspeccionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mantenimiento': {
      id: '/mantenimiento'
      path: '/mantenimiento'
      fullPath: '/mantenimiento'
      preLoaderRoute: typeof MantenimientoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historial': {
      id: '/historial'
      path: '/historial'
      fullPath: '/historial'
      preLoaderRoute: typeof HistorialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipos': {
      id: '/equipos'
      path: '/equipos'
      fullPath: '/equipos'
      preLoaderRoute: typeof EquiposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cambiar-password': {
      id: '/cambiar-password'
      path: '/cambiar-password'
      fullPath: '/cambiar-password'
      preLoaderRoute: typeof CambiarPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mantenimiento/': {
      id: '/mantenimiento/'
      path: '/'
      fullPath: '/mantenimiento/'
      preLoaderRoute: typeof MantenimientoIndexRouteImport
      parentRoute: typeof MantenimientoRoute
    }
    '/mantenimiento/parametros': {
      id: '/mantenimiento/parametros'
      path: '/parametros'
      fullPath: '/mantenimiento/parametros'
      preLoaderRoute: typeof MantenimientoParametrosRouteImport
      parentRoute: typeof MantenimientoRoute
    }
    '/mantenimiento/equipos-externos': {
      id: '/mantenimiento/equipos-externos'
      path: '/equipos-externos'
      fullPath: '/mantenimiento/equipos-externos'
      preLoaderRoute: typeof MantenimientoEquiposExternosRouteImport
      parentRoute: typeof MantenimientoRoute
    }
    '/mantenimiento/$id': {
      id: '/mantenimiento/$id'
      path: '/$id'
      fullPath: '/mantenimiento/$id'
      preLoaderRoute: typeof MantenimientoIdRouteImport
      parentRoute: typeof MantenimientoRoute
    }
    '/inspeccion/$id': {
      id: '/inspeccion/$id'
      path: '/inspeccion/$id'
      fullPath: '/inspeccion/$id'
      preLoaderRoute: typeof InspeccionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mantenimiento/nuevo/$tipo': {
      id: '/mantenimiento/nuevo/$tipo'
      path: '/nuevo/$tipo'
      fullPath: '/mantenimiento/nuevo/$tipo'
      preLoaderRoute: typeof MantenimientoNuevoTipoRouteImport
      parentRoute: typeof MantenimientoRoute
    }
  }
}

interface MantenimientoRouteChildren {
  MantenimientoIdRoute: typeof MantenimientoIdRoute
  MantenimientoEquiposExternosRoute: typeof MantenimientoEquiposExternosRoute
  MantenimientoParametrosRoute: typeof MantenimientoParametrosRoute
  MantenimientoIndexRoute: typeof MantenimientoIndexRoute
  MantenimientoNuevoTipoRoute: typeof MantenimientoNuevoTipoRoute
}

const MantenimientoRouteChildren: MantenimientoRouteChildren = {
  MantenimientoIdRoute: MantenimientoIdRoute,
  MantenimientoEquiposExternosRoute: MantenimientoEquiposExternosRoute,
  MantenimientoParametrosRoute: MantenimientoParametrosRoute,
  MantenimientoIndexRoute: MantenimientoIndexRoute,
  MantenimientoNuevoTipoRoute: MantenimientoNuevoTipoRoute,
}

const MantenimientoRouteWithChildren = MantenimientoRoute._addFileChildren(
  MantenimientoRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  CambiarPasswordRoute: CambiarPasswordRoute,
  EquiposRoute: EquiposRoute,
  HistorialRoute: HistorialRoute,
  MantenimientoRoute: MantenimientoRouteWithChildren,
  InspeccionIdRoute: InspeccionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
